version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: picpay_simplificado
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

networks:
  db-network:
    driver: bridge

